@startuml UseCase_Diagram
left to right direction
skinparam packageStyle rectangle

actor "Usuario del Comedor" as User
actor "Estudiante" as Student
actor "Empleado" as Employee
actor "Administrador" as Admin

User -[hidden]left- Student
Student -[hidden]left- Employee

User <|-- Student
User <|-- Employee

package "Sistema de Comedor Universitario" {

    usecase "Iniciar Sesión" as UC_Login
    usecase "Registrarse" as UC_Register

    usecase "Consultar Menús" as UC_Menu
    usecase "Solicitar turno" as UC_Reserva

    usecase "Planificar Menú Semanal" as UC_GestMenu
    usecase "Registrar Consumo Diario" as UC_Consumo
    usecase "Generar Reportes" as UC_Reports

    User --> UC_Login
    User --> UC_Menu
    User --> UC_Reserva

    UC_Login ..> UC_Register : <<extend>>

    Admin --> UC_GestMenu
    Admin --> UC_Consumo
    Admin --> UC_Reports
}
@enduml